### ISSUE TITLE
Please either provide a working Google Closure jar or wrap localStorage

### ISSUE THREAD

**Issue by robert-stuttaford** [shoreleave/shoreleave-browser#1]
I can't use any shoreleave project that uses browser (eg, remote) until localStorage is properly wrapped OR you can provide your super secret home-made google closure jar :-)

I know you fixed it in pubsub, but now that i'm trying to use remote (which pulls in browser), I'm back where I started.

Help!

**Comment by ohpauleez** [comment]
Gah!  I'm sorry you got caught on this again.  It shouldn't be happening in remote, can you post the error you're getting?

**Comment by robert-stuttaford** [comment]
Apologies. I tried again and now I'm unable to reproduce the issue! Closing for now :-)
