### ISSUE TITLE
Issue with code providing of "goog.storage.mechanism.HTML5LocalStorage"

### ISSUE THREAD

**Issue by franks42** [shoreleave/shoreleave-browser#3]
In the latest and greatest you have turned-on the local storage support again, which is great,
but I get those:

---

ERROR - required "goog.storage.mechanism.HTML5LocalStorage" namespace never provided
goog.require('goog.storage.mechanism.HTML5LocalStorage')

---

When I peek in the generated main-debug.js, then there is no code included/provided for goog.storage.mechanism.HTML5LocalStorage.

Believe this issue has been mentioned before.

Kind of puzzling... as your code seems pretty innocent (?)

-FrankS.

**Comment by ohpauleez** [comment]
Yeah, I'm getting the error too - master won't be stable for another week or so.  I need to update the reference to the third-party jar in the latest CLJS.  I also want to make more things optional (explicit inclusion) - LocalStorage will be one of those things.

**Comment by franks42** [comment]
A dependency in my project.clj on domina 1.0.0 pulled in a goog-jar-_.jar file, which didn't work well with the google-closure-library-_.jar.

Seems that goog-jar was providing similar access to the goog.\* modules as the google-closure-library, 
but was hopelessly outdated… no html5 goog-files in goog-jar but they are present in the google-closure-library.

Removing the domina dependency made the goog-jar file go away, and all goog requires and provides are happily resolved - and the shoreleave browser module at least loads ;-)

Ough… talking about dependency hell...

Closing the issue - sorry for the confusion.

-FrankS.
